import { CONFIG } from '../content/config';
import type { GameState, Num, PuzzleState } from './types';

// The Load Balancer — a lights-out grid. Each district is over-loaded (lit) or
// balanced (dark); tapping a district flips it AND its orthogonal neighbors.
// Goal: balance the whole grid (all dark). Snappy, tactile, always solvable
// (generated by tapping out from the solved state), difficulty scales by tier.

function neighbor(idx: number, dir: number, size: number): number | null {
  const x = idx % size;
  const y = Math.floor(idx / size);
  if (dir === 0) return y > 0 ? idx - size : null;
  if (dir === 1) return x < size - 1 ? idx + 1 : null;
  if (dir === 2) return y < size - 1 ? idx + size : null;
  return x > 0 ? idx - 1 : null;
}

/** Flip a district and its orthogonal neighbors. */
function toggle(cells: boolean[], idx: number, size: number): void {
  cells[idx] = !cells[idx];
  for (const d of [0, 1, 2, 3]) {
    const nb = neighbor(idx, d, size);
    if (nb !== null) cells[nb] = !cells[nb];
  }
}

export function puzzleSize(tier: number): number {
  return Math.min(4 + Math.floor(tier / 2), 7);
}

/** Cells lit around a district if you tapped it — for the UI's tap preview. */
export function affectedCells(idx: number, size: number): number[] {
  const out = [idx];
  for (const d of [0, 1, 2, 3]) {
    const nb = neighbor(idx, d, size);
    if (nb !== null) out.push(nb);
  }
  return out;
}

/**
 * Deal a fresh board: start balanced (all dark) and tap random districts.
 * Any board reached by tapping is solvable by tapping the same cells, so it's
 * always winnable. `par` = the minimal tap set (cells tapped an odd number of
 * times), the target for the efficiency bonus.
 */
export function newPuzzle(tier: number, rand: () => number = Math.random): PuzzleState {
  const size = puzzleSize(tier);
  const n = size * size;
  const cells = new Array<boolean>(n).fill(false);
  const solution = new Array<boolean>(n).fill(false);
  const taps = 3 + tier + Math.floor(size * 1.2);
  for (let k = 0; k < taps; k++) {
    const c = Math.floor(rand() * n);
    toggle(cells, c, size);
    solution[c] = !solution[c];
  }
  // Never hand the player an already-balanced board.
  if (cells.every((v) => !v)) {
    const c = Math.floor(rand() * n);
    toggle(cells, c, size);
    solution[c] = !solution[c];
  }
  const par = solution.filter(Boolean).length;
  return { tier, size, cells, moves: 0, par: Math.max(1, par), solved: false };
}

export function isSolved(p: PuzzleState): boolean {
  return p.cells.every((v) => !v);
}

/** Credits for a manual solve; near-par solves earn the efficiency bonus. */
export function puzzleReward(tier: number, moves: number, par: number): Num {
  const base = CONFIG.PUZZLE_BASE_REWARD + CONFIG.PUZZLE_TIER_REWARD * tier;
  return moves <= par + CONFIG.PUZZLE_BONUS_SLACK ? Math.round(base * CONFIG.PUZZLE_BONUS_MULT) : base;
}

export interface SolveResult {
  reward: Num;
  bonus: boolean;
}

/**
 * Tap a district (flips it + neighbors). If that balances the whole grid: pay
 * Credits, extend the Grid Surge, and latch `solved` (further taps ignored
 * until the player deals a new board).
 */
export function tapCell(s: GameState, idx: number): SolveResult | null {
  const p = s.puzzle;
  if (idx < 0 || idx >= p.cells.length || p.solved) return null;
  toggle(p.cells, idx, p.size);
  p.moves += 1;
  if (!isSolved(p)) return null;
  p.solved = true;
  const bonus = p.moves <= p.par + CONFIG.PUZZLE_BONUS_SLACK;
  const reward = puzzleReward(p.tier, p.moves, p.par);
  s.credits += reward;
  s.boosts.surgeLeft = Math.min(CONFIG.SURGE_CAP_SECONDS, s.boosts.surgeLeft + CONFIG.SURGE_MANUAL_SECONDS);
  s.stats.puzzlesSolved += 1;
  return { reward, bonus };
}

/**
 * Auto-solvers grind boards in the background: reduced Credits and a shorter
 * surge per solve. Enough of them keep the surge lit permanently — the layer
 * "plays itself".
 */
export function runSolvers(s: GameState, dt: number): void {
  if (s.solvers <= 0) return;
  s.solverProgress += (s.solvers * dt) / CONFIG.SOLVER_SECONDS;
  const n = Math.floor(s.solverProgress);
  if (n <= 0) return;
  s.solverProgress -= n;
  const base = CONFIG.PUZZLE_BASE_REWARD + CONFIG.PUZZLE_TIER_REWARD * s.tier;
  s.credits += n * Math.round(base * CONFIG.SOLVER_REWARD_FACTOR);
  s.boosts.surgeLeft = Math.min(CONFIG.SURGE_CAP_SECONDS, s.boosts.surgeLeft + n * CONFIG.SURGE_AUTO_SECONDS);
  s.stats.puzzlesSolved += n;
}
